namespace Fu
{
    public enum FuColors
    {
        // Imgui colors
        Text = 0,
        TextDisabled = 1,
        WindowBg = 2,
        ChildBg = 3,
        PopupBg = 4,
        Border = 5,
        BorderShadow = 6,
        FrameBg = 7,
        FrameBgHovered = 8,
        FrameBgActive = 9,
        TitleBg = 10,
        TitleBgActive = 11,
        TitleBgCollapsed = 12,
        MenuBarBg = 13,
        ScrollbarBg = 14,
        ScrollbarGrab = 15,
        ScrollbarGrabHovered = 16,
        ScrollbarGrabActive = 17,
        CheckMark = 18,
        SliderGrab = 19,
        SliderGrabActive = 20,
        Button = 21,
        ButtonHovered = 22,
        ButtonActive = 23,
        Header = 24,
        HeaderHovered = 25,
        HeaderActive = 26,
        Separator = 27,
        SeparatorHovered = 28,
        SeparatorActive = 29,
        ResizeGrip = 30,
        ResizeGripHovered = 31,
        ResizeGripActive = 32,
        TabHovered = 33,
        Tab = 34,
        TabSelected = 35,
        TabSelectedOverline = 36,
        TabDimmed = 37,
        TabDimmedSelected = 38,
        TabDimmedSelectedOverline = 39,
        DockingPreview = 40,
        DockingEmptyBg = 41,
        PlotLines = 42,
        PlotLinesHovered = 43,
        PlotHistogram = 44,
        PlotHistogramHovered = 45,
        TableHeaderBg = 46,
        TableBorderStrong = 47,
        TableBorderLight = 48,
        TableRowBg = 49,
        TableRowBgAlt = 50,
        TextLink = 51,
        TextSelectedBg = 52,
        DragDropTarget = 53,
        NavCursor = 54,
        NavWindowingHighlight = 55,
        NavWindowingDimBg = 56,
        ModalWindowDimBg = 57,

        // FuGui colors
        Highlight = 58,
        HighlightHovered = 59,
        HighlightActive = 60,
        HighlightDisabled = 61,

        FrameHoverFeedback = 62,
        FrameSelectedFeedback = 63,

        Collapsable = 64,
        CollapsableHovered = 65,
        CollapsableActive = 66,
        CollapsableDisabled = 67,

        Selected = 68,
        SelectedHovered = 69,
        SelectedActive = 70,
        SelectedText = 71,

        Knob = 72,
        KnobHovered = 73,
        KnobActive = 74,

        MainMenuText = 75,
        HighlightText = 76,
        HighlightTextDisabled = 77,

        TextInfo = 78,
        TextDanger = 79,
        TextWarning = 80,
        TextSuccess = 81,

        BackgroundInfo = 82,
        BackgroundDanger = 83,
        BackgroundWarning = 84,
        BackgroundSuccess = 85,

        HoveredWindowTab = 86,

        DuotonePrimaryColor = 87,
        DuotoneSecondaryColor = 88,

        // Nodes
        NodeHeader = 89,
        NodePort = 90,
        NodeEdge = 91,
        NodeGridMinor = 92,
        NodeGridMajor = 93,
        NodeLinkPreview = 94,
        NodeSelectedEdge = 95,
        NodeHoveredEdge = 96,
        NodeSelectedBorder = 97,

        COUNT = 98
    }
}