using System.Runtime.CompilerServices;

namespace Fu.Framework
{
    public class Icons : FuIcons
    {
        protected static string _Datafusion_duotone = "\uECE4";
        public static string Datafusion_duotone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Datafusion_duotone; }
        protected static string _Datafusion_solid = "\uE065";
        public static string Datafusion_solid { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Datafusion_solid; }
        protected static string _Datafusion_light = "\uE066";
        public static string Datafusion_light { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Datafusion_light; }
        protected static string _Environment = "\uE067";
        public static string Environment { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Environment; }
        protected static string _Ghost = "\uE068";
        public static string Ghost { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Ghost; }
        protected static string _Show = "\uE069";
        public static string Show { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Show; }
        protected static string _Hide = "\uE06A";
        public static string Hide { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Hide; }
        protected static string _CursorSelection_duotone = "\uECE6";
        public static string CursorSelection_duotone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _CursorSelection_duotone; }
        protected static string _CursorSelection_light = "\uE06B";
        public static string CursorSelection_light { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _CursorSelection_light; }
        protected static string _EditShapes = "\uE06C";
        public static string EditShapes { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _EditShapes; }
        protected static string _Focus = "\uECE8";
        public static string Focus { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Focus; }
        protected static string _Note = "\uE06D";
        public static string Note { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Note; }
        protected static string _Measure = "\uE06E";
        public static string Measure { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Measure; }
        protected static string _Resources = "\uE06F";
        public static string Resources { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Resources; }
        protected static string _Import = "\uECEA";
        public static string Import { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Import; }
        protected static string _Export = "\uECEC";
        public static string Export { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Export; }
        protected static string _PointView = "\uECEE";
        public static string PointView { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _PointView; }
        protected static string _Capture = "\uECF0";
        public static string Capture { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Capture; }
        protected static string _Captures_duotone = "\uECF2";
        public static string Captures_duotone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Captures_duotone; }
        protected static string _Captures_solid = "\uE070";
        public static string Captures_solid { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Captures_solid; }
        protected static string _Materials_duotone = "\uECF4";
        public static string Materials_duotone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Materials_duotone; }
        protected static string _Materials_solid = "\uE071";
        public static string Materials_solid { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Materials_solid; }
        protected static string _Groups_duotone = "\uECF6";
        public static string Groups_duotone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Groups_duotone; }
        protected static string _Groups_solid = "\uE072";
        public static string Groups_solid { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Groups_solid; }
        protected static string _Displacement_duotone = "\uECF8";
        public static string Displacement_duotone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Displacement_duotone; }
        protected static string _Displacement_solid = "\uE073";
        public static string Displacement_solid { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Displacement_solid; }
        protected static string _Pointcloud = "\uECFA";
        public static string Pointcloud { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Pointcloud; }
        protected static string _CameraVideo_duotone = "\uECFC";
        public static string CameraVideo_duotone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _CameraVideo_duotone; }
        protected static string _CameraVideo_light = "\uE074";
        public static string CameraVideo_light { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _CameraVideo_light; }
        protected static string _CameraVideo_solid = "\uE075";
        public static string CameraVideo_solid { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _CameraVideo_solid; }
        protected static string _CameraPhoto_duotone = "\uECFE";
        public static string CameraPhoto_duotone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _CameraPhoto_duotone; }
        protected static string _CameraPhoto_light = "\uE076";
        public static string CameraPhoto_light { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _CameraPhoto_light; }
        protected static string _FEM = "\uED00";
        public static string FEM { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _FEM; }
        protected static string _Filter_duotone = "\uED02";
        public static string Filter_duotone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Filter_duotone; }
        protected static string _Filter_solid = "\uE077";
        public static string Filter_solid { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Filter_solid; }
        protected static string _Percent_duotone = "\uED04";
        public static string Percent_duotone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Percent_duotone; }
        protected static string _Percent_solid = "\uE078";
        public static string Percent_solid { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Percent_solid; }
        protected static string _Magic_duotone = "\uED06";
        public static string Magic_duotone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Magic_duotone; }
        protected static string _Magic_solid = "\uE079";
        public static string Magic_solid { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Magic_solid; }
        protected static string _Pipeline3DX = "\uED08";
        public static string Pipeline3DX { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Pipeline3DX; }
        protected static string _Info_duotone = "\uED0A";
        public static string Info_duotone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Info_duotone; }
        protected static string _Info_solid = "\uE07A";
        public static string Info_solid { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Info_solid; }
        protected static string _InfoCircle = "\uED0C";
        public static string InfoCircle { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _InfoCircle; }
        protected static string _Play_duotone = "\uED0E";
        public static string Play_duotone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Play_duotone; }
        protected static string _Play_solid = "\uE07B";
        public static string Play_solid { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Play_solid; }
        protected static string _PlayPause_duotone = "\uED10";
        public static string PlayPause_duotone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _PlayPause_duotone; }
        protected static string _PlayPause_solid = "\uE07C";
        public static string PlayPause_solid { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _PlayPause_solid; }
        protected static string _Pause_duotone = "\uED12";
        public static string Pause_duotone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Pause_duotone; }
        protected static string _Pause_solid = "\uE07D";
        public static string Pause_solid { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Pause_solid; }
        protected static string _Stop_duotone = "\uED14";
        public static string Stop_duotone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Stop_duotone; }
        protected static string _Stop_solid = "\uE07E";
        public static string Stop_solid { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Stop_solid; }
        protected static string _ArrowUp_duotone = "\uED16";
        public static string ArrowUp_duotone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _ArrowUp_duotone; }
        protected static string _ArrowUp_solid = "\uE07F";
        public static string ArrowUp_solid { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _ArrowUp_solid; }
        protected static string _ArrowDown_duotone = "\uED18";
        public static string ArrowDown_duotone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _ArrowDown_duotone; }
        protected static string _ArrowDown_solid = "\uE080";
        public static string ArrowDown_solid { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _ArrowDown_solid; }
        protected static string _ArrowLeft_duotone = "\uED1A";
        public static string ArrowLeft_duotone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _ArrowLeft_duotone; }
        protected static string _ArrowLeft_solid = "\uE081";
        public static string ArrowLeft_solid { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _ArrowLeft_solid; }
        protected static string _ArrowRight_duotone = "\uED1C";
        public static string ArrowRight_duotone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _ArrowRight_duotone; }
        protected static string _ArrowRight_solid = "\uE082";
        public static string ArrowRight_solid { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _ArrowRight_solid; }
        protected static string _Close = "\uE083";
        public static string Close { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Close; }
        protected static string _Delete = "\uED1E";
        public static string Delete { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Delete; }
        protected static string _Back = "\uED20";
        public static string Back { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Back; }
        protected static string _FolderOpen = "\uED22";
        public static string FolderOpen { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _FolderOpen; }
        protected static string _Link_duotone = "\uED24";
        public static string Link_duotone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Link_duotone; }
        protected static string _Link_solide = "\uE084";
        public static string Link_solide { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Link_solide; }
        protected static string _Lock = "\uED26";
        public static string Lock { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Lock; }
        protected static string _Unlock_duotone = "\uED28";
        public static string Unlock_duotone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Unlock_duotone; }
        protected static string _Unlock_light = "\uE085";
        public static string Unlock_light { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Unlock_light; }
        protected static string _Plus_duotone = "\uED2A";
        public static string Plus_duotone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Plus_duotone; }
        protected static string _Plus_solid = "\uE086";
        public static string Plus_solid { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Plus_solid; }
        protected static string _Settings_solid = "\uE087";
        public static string Settings_solid { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Settings_solid; }
        protected static string _SettingsPreferences = "\uED2E";
        public static string SettingsPreferences { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _SettingsPreferences; }
        protected static string _Refresh = "\uED30";
        public static string Refresh { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Refresh; }
        protected static string _Undo_duotone = "\uED32";
        public static string Undo_duotone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Undo_duotone; }
        protected static string _Undo_solid = "\uE088";
        public static string Undo_solid { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Undo_solid; }
        protected static string _Redo_duotone = "\uED34";
        public static string Redo_duotone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Redo_duotone; }
        protected static string _Redo_solid = "\uE089";
        public static string Redo_solid { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Redo_solid; }
        protected static string _Open = "\uED36";
        public static string Open { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Open; }
        protected static string _Duplicate = "\uED38";
        public static string Duplicate { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Duplicate; }
        protected static string _Search = "\uED3A";
        public static string Search { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Search; }
        protected static string _MenuDots = "\uED3C";
        public static string MenuDots { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _MenuDots; }
        protected static string _Save = "\uED3E";
        public static string Save { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Save; }
        protected static string _Warning = "\uED40";
        public static string Warning { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Warning; }
        protected static string _Error = "\uED42";
        public static string Error { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Error; }
        protected static string _CheckV = "\uE08A";
        public static string CheckV { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _CheckV; }
        protected static string _Light = "\uE08B";
        public static string Light { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Light; }
        protected static string _Screen_solid = "\uE08C";
        public static string Screen_solid { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Screen_solid; }
        protected static string _Sealant = "\uED46";
        public static string Sealant { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Sealant; }
        protected static string _SubTask = "\uED48";
        public static string SubTask { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _SubTask; }
        protected static string _Restore = "\uED4A";
        public static string Restore { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Restore; }
        protected static string _Position = "\uED4C";
        public static string Position { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Position; }
        protected static string _GalacticRendering_duotone = "\uED4E";
        public static string GalacticRendering_duotone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _GalacticRendering_duotone; }
        protected static string _GalacticRendering_solid = "\uE08D";
        public static string GalacticRendering_solid { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _GalacticRendering_solid; }
        protected static string _Global = "\uE08E";
        public static string Global { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Global; }
        protected static string _Local = "\uE08F";
        public static string Local { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Local; }
        protected static string _Click = "\uE090";
        public static string Click { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Click; }
        protected static string _Native = "\uE091";
        public static string Native { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Native; }
        protected static string _Center = "\uE092";
        public static string Center { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Center; }
        protected static string _Console_duotone = "\uED50";
        public static string Console_duotone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Console_duotone; }
        protected static string _Console_solid = "\uE093";
        public static string Console_solid { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Console_solid; }
        protected static string _LinkOrigin = "\uED52";
        public static string LinkOrigin { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _LinkOrigin; }
        protected static string _Unlink = "\uED54";
        public static string Unlink { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Unlink; }
        protected static string _TreeList_duotone = "\uED56";
        public static string TreeList_duotone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _TreeList_duotone; }
        protected static string _TreeList_solid = "\uE094";
        public static string TreeList_solid { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _TreeList_solid; }
        protected static string _Dmu = "\uE095";
        public static string Dmu { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Dmu; }
        protected static string _Farovite_duotone = "\uED58";
        public static string Farovite_duotone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Farovite_duotone; }
        protected static string _Farovite_solid = "\uE096";
        public static string Farovite_solid { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Farovite_solid; }
        protected static string _Plug = "\uED5A";
        public static string Plug { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Plug; }
        protected static string _LoopPlay_duotone = "\uED5C";
        public static string LoopPlay_duotone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _LoopPlay_duotone; }
        protected static string _LoopPlay_solid = "\uE097";
        public static string LoopPlay_solid { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _LoopPlay_solid; }
        protected static string _Thermometer_duotone = "\uED5E";
        public static string Thermometer_duotone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Thermometer_duotone; }
        protected static string _Thermometer_solid = "\uE098";
        public static string Thermometer_solid { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Thermometer_solid; }
        protected static string _Edit_duotone = "\uED60";
        public static string Edit_duotone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Edit_duotone; }
        protected static string _Edit_light = "\uE099";
        public static string Edit_light { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Edit_light; }
        protected static string _Box = "\uE09A";
        public static string Box { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Box; }
        protected static string _Cube = "\uE09B";
        public static string Cube { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Cube; }
        protected static string _Physics_duotone = "\uED62";
        public static string Physics_duotone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Physics_duotone; }
        protected static string _Physics_solid = "\uE09C";
        public static string Physics_solid { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Physics_solid; }
        protected static string _Excel = "\uED64";
        public static string Excel { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Excel; }
        protected static string _Database = "\uED66";
        public static string Database { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Database; }
        protected static string _Themes = "\uED68";
        public static string Themes { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Themes; }
        protected static string _Alignment = "\uED6A";
        public static string Alignment { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Alignment; }
        protected static string _Dispatch = "\uED6C";
        public static string Dispatch { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Dispatch; }
        protected static string _Propagation = "\uED6E";
        public static string Propagation { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Propagation; }
        protected static string _LocationLocked = "\uE09D";
        public static string LocationLocked { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _LocationLocked; }
        protected static string _Clear_duotone = "\uED70";
        public static string Clear_duotone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Clear_duotone; }
        protected static string _Clear_light = "\uE09E";
        public static string Clear_light { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Clear_light; }
        protected static string _Scene_light = "\uE09F";
        public static string Scene_light { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Scene_light; }
        protected static string _Scene_duotone = "\uED72";
        public static string Scene_duotone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Scene_duotone; }
        protected static string _Container_light = "\uE0A0";
        public static string Container_light { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Container_light; }
        protected static string _Container_duotone = "\uED74";
        public static string Container_duotone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Container_duotone; }
        protected static string _MechanicalAnalysis_duotone = "\uED76";
        public static string MechanicalAnalysis_duotone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _MechanicalAnalysis_duotone; }
        protected static string _MechanicalAnalysis_solid = "\uE0A1";
        public static string MechanicalAnalysis_solid { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _MechanicalAnalysis_solid; }
        protected static string _DmuLoaded = "\uE0A2";
        public static string DmuLoaded { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _DmuLoaded; }
        protected static string _DmuUnloaded = "\uE0A3";
        public static string DmuUnloaded { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _DmuUnloaded; }
        protected static string _PointerDisabled = "\uE0A4";
        public static string PointerDisabled { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _PointerDisabled; }
        protected static string _MCI = "\uE0A5";
        public static string MCI { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _MCI; }
        protected static string _DragonflyLogo = "\uE0A6";
        public static string DragonflyLogo { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _DragonflyLogo; }
        protected static string _Gizmos = "\uE0A7";
        public static string Gizmos { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Gizmos; }
        protected static string _NormalView = "\uE0A8";
        public static string NormalView { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _NormalView; }
        protected static string _Sections = "\uE0A9";
        public static string Sections { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Sections; }
        protected static string _Panel = "\uE0AA";
        public static string Panel { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Panel; }
        protected static string _Cube_legacy = "\uE0AB";
        public static string Cube_legacy { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Cube_legacy; }
        protected static string _Sphere = "\uE0AC";
        public static string Sphere { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Sphere; }
        protected static string _Cylinder = "\uE0AD";
        public static string Cylinder { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Cylinder; }
        protected static string _Cone = "\uE0AE";
        public static string Cone { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Cone; }
        protected static string _ConeTruncated = "\uE0AF";
        public static string ConeTruncated { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _ConeTruncated; }
        protected static string _ConeHollow = "\uE0B0";
        public static string ConeHollow { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _ConeHollow; }
        protected static string _Torus = "\uE0B1";
        public static string Torus { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Torus; }
        protected static string _Prism = "\uE0B2";
        public static string Prism { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Prism; }
        protected static string _Paraboloid = "\uE0B3";
        public static string Paraboloid { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Paraboloid; }
        protected static string _Stairs = "\uE0B4";
        public static string Stairs { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Stairs; }
        protected static string _Door = "\uE0B5";
        public static string Door { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Door; }
        protected static string _StairsCurved = "\uE0B6";
        public static string StairsCurved { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _StairsCurved; }
        protected static string _Arch = "\uE0B7";
        public static string Arch { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Arch; }
        protected static string _Pipe = "\uE0B8";
        public static string Pipe { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Pipe; }
        protected static string _Bend = "\uE0B9";
        public static string Bend { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Bend; }
        protected static string _Assembly = "\uE0BA";
        public static string Assembly { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Assembly; }
        protected static string _Part = "\uE0BB";
        public static string Part { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => _Part; }
    }
}